Test/patch accounts user
Brunoro811/capstone-q4-django pull request #19
Opened 2022-05-26 14:28 UTC by juliagamaol

2022-05-26 15:52 UTC, Brunoro811 requested changes

2022-05-26 15:52 UTC, Brunoro811 commented on accounts/migrations/0001_initial.py
> +
deletar migrations

2022-05-26 16:16 UTC, juliagamaol reviewed
deleted

2022-05-26 16:18 UTC, Brunoro811 approved these changes

2022-05-26 19:42 UTC, Poketnans requested changes

2022-05-26 19:42 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        response = self.client.patch(f"/accounts/{self.seller.id}", self.seller_data,format="json")
Adicionar uma barra no final da url, pois pode dar erro na hora de rodar os testes.

2022-05-26 19:42 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        response = self.client.patch(f"/accounts/{self.seller.id}", self.seller_data,format="json")
Adicionar uma barra no final da url.

2022-05-26 19:42 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        response = self.client.patch(f"/accounts/{self.seller.id}", self.seller_data,format="json")
Adicionar uma barra no final da url.

2022-05-26 19:42 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        response = self.client.patch(f"/accounts/230d81bf-2092-420a-a310-505ed9a1c243", self.seller_data, format="json")
Adicionar uma barra no final da url.

2022-05-26 19:42 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        response = self.client.patch(f"/accounts/{self.seller.id}", data, format="json")
Adicionar uma barra no final da url.

2022-05-26 19:42 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        response = self.client.patch(f"/accounts/{self.seller.id}", data, format="json")
Adicionar uma barra no final da url.

2022-05-26 20:20 UTC, Poketnans requested changes

2022-05-26 20:20 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        self.assertIn("detail", response.json())
No Backlog, não há a chave `detail` na resposta de erro de `email`. No caso deveria ter a chave `email`.

2022-05-26 20:20 UTC, Poketnans commented on accounts/tests/integration/tests_patch_accounts_user_id.py
> +        self.assertIn("detail", response.json())
No Backlog, não há a chave `detail` na resposta de erro de `username`. No caso deveria ter a chave `username`.

2022-05-26 20:28 UTC, juliagamaol reviewed
ok

2022-05-27 00:29 UTC, Poketnans approved these changes
Show. Agora deu bom!

2022-05-27 01:50 UTC, pedromenimen approved these changes

2022-05-27 14:55 UTC, merged