Feature/create model orders
Brunoro811/capstone-q4-django pull request #57
Opened 2022-06-01 21:37 UTC by Brunoro811

2022-06-01 21:56 UTC, Poketnans requested changes

2022-06-01 21:56 UTC, Poketnans commented on orders/models.py
> +    order_id = models.ForeignKey("orders.OrdersModel", on_delete=models.PROTECT)
Como não vai pra documentação, pode deixar como `order`

2022-06-01 21:56 UTC, Poketnans commented on orders/models.py
> +    seller_id = models.ForeignKey("accounts.AccountModel", on_delete=models.PROTECT,related_name="+")
Como a model não vai ser construída diretamente com o que vier na requisição, pode deixar como `seller`.

2022-06-01 21:56 UTC, Poketnans commented on orders/models.py
> +    store_id = models.ForeignKey("stores.StoreModel", on_delete=models.PROTECT,related_name="+")
Como a model não vai ser construída diretamente com o que vier na requisição, pode deixar como `store`.

2022-06-02 13:04 UTC, pedromenimen approved these changes

2022-06-02 13:05 UTC, merged